export const Keywords = [
    'fn',    // Function declaration: fn <identifier>[.<identifier>...] (<parameters>): \n <body>
    'on',    // Event hook: on <event> (<parameters>): \n <body>
    'if',
    'else',
    'do',
    'while',
    'for',
    'in',
    'break',
    'continue',
    'return',
    'true',
    'false',
    'null',
    'not',
    'this',
    'and',
    'or',
    'local',
    'public',
    'import',
    'wait',
    'new',
    'blueprint',
    'extends',
    'parent',
] as const;
